import Head from 'next/head';

export default function Terms() {
  const message = 'Terms and Conditions';
  const message2 = '1. Acceptance of Terms';
  const message3 = '2. User Responsibilities';
  const message4 = '3. Reporting Vulnerabilities';
  const message5 = '4. Rewards';
  const message6 = '5. Limitation of Liability';
  const message7 = '6. Changes to Terms';
  const message8 = '7. Governing Law';


  return (
    <div className="container">
      <Head>
        <title>Terms and Conditions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">   

        <h1>{message}</h1>
        <br></br>
        <h2>{message2}</h2>
        <h3>By accessing and using the Bounty Nexus platform, you confirm your acceptance of these Terms and Conditions. If you do not agree to these terms, you must refrain from using the website.</h3>
        
        <h2>{message3}</h2>
        <h3>As a user, you agree to:
            - Provide accurate and complete information during registration and reporting.<br></br>
            - Use the platform solely for legitimate purposes related to vulnerability reporting.<br></br>
            - Not engage in any form of harassment, abuse, or illegal activity.<br></br>
            - Maintain the confidentiality of your account credentials and notify Bounty Nexus immediately of any unauthorized use of your account.<br></br></h3>

        <h2>{message4}</h2>
        <h3>Users are encouraged to report vulnerabilities they discover. Reports must be submitted through the designated channels and should include:<br></br>

            - A clear description of the vulnerability.<br></br>
            - Steps to reproduce the issue.<br></br>
            - Any relevant screenshots or logs.<br></br>
            - A suggested impact assessment.<br></br></h3>
        <h2>{message5}</h2>
        <h3>Rewards for reported vulnerabilities will be determined by the respective company based on criteria such as:<br></br>

            - Severity of the vulnerability.<br></br>
            - Potential impact on user data and security.<br></br>
            - Quality of the report and reproducibility of the issue.<br></br>

            Bounty Nexus is not responsible for the distribution of rewards, which are solely at the discretion of the involved company.</h3>
        <h2>{message6}</h2>
        <h3>Bounty Nexus is not liable for any direct, indirect, incidental, or consequential damages resulting from your use or inability to use the platform. You acknowledge that the use of any information obtained through the platform is at your own risk.</h3>
        <h2>{message7}</h2>
        <h3>We reserve the right to modify these Terms at any time. Users will be notified of significant changes via email or through a notice on the website. Your continued use of the platform after changes are implemented signifies your acceptance of the new Terms.</h3>
        <h2>{message8}</h2>
        <h3>These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which Bounty Nexus operates, without regard to its conflict of law principles.</h3>
      </main>
    </div>
  );
}