import Head from 'next/head';

export default function PrivacyPolicy() {
  const message = 'Privacy Policy';
  const message2 = '1. Information Collection';
  const message3 = '2. Use of Information';
  const message4 = '3. Data Protection';
  const message5 = '4. Third-Party Disclosure';
  const message6 = '5. User Rights';
  const message7 = '6. Data Retention';
  // const message8 = '7. Governing Law';


  return (
    <div className="container">
      <Head>
        <title>Privacy Policy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">   

        <h1>{message}</h1>
        <br></br>
        <h2>{message2}</h2>
        <h3>We collect personal information that you voluntarily provide when you register for an account, submit vulnerability reports, or interact with our services. This may include your name, email address, and other relevant details.</h3>
        
        <h2>{message3}</h2>
        <h3>Your information is primarily used to:<br></br>

            - Create and maintain your user account.<br></br>
            - Communicate with you regarding vulnerability submissions and rewards.<br></br>
            - Improve our services and user experience.<br></br>
            - Comply with legal obligations and enforce our Terms and Conditions.</h3>

        <h2>{message4}</h2>
        <h3>We implement a variety of security measures to protect your personal information. This includes encryption, secure servers, and access controls to prevent unauthorized access.</h3>
        <h2>{message5}</h2>
        <h3>We do not sell or rent your personal information to third parties. Your data may be shared with companies involved in the resolution of reported vulnerabilities for the purpose of investigation and reward distribution.</h3>
        <h2>{message6}</h2>
        <h3>You have the right to:<br></br>

            - Access your personal information.<br></br>
            - Request correction of any inaccurate information.<br></br>
            - Delete your account and personal data, subject to our policies and legal obligations.
        </h3>
        <h2>{message7}</h2>
        <h3>We retain your information only as long as necessary to fulfill the purposes outlined in this policy or as required by law.
        </h3>
        {/* <h2>{message8}</h2>
        <h3>These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which Bounty Nexus operates, without regard to its conflict of law principles.</h3> */}
      </main>
    </div>
  );
}